#!/bin/bash
### BEGIN INIT INFO
# Provides:          qdisc
# Required-Start:    mountkernfs $local_fs $network $syslog $networking $ifupdown
# Required-Stop:     $local_fs
# X-Start-Before:    $vboxdrv $virtualbox $libvirt-bin $libvirtd $vmware $fail2ban
# X-Stop-After:      $network
# Default-Start:     S 1 2 3 4 5
# Default-Stop:      0 6
# Short-Description: provides qos tuning
# Description:       sets up multiple QoS tuning parameters for enhanced network performance
### END INIT INFO
# (c) 2016 Leif Sawyer
# License: GPL 3.0 (see https://github.com/akhepcat/)
# Permanent home:  https://github.com/akhepcat/qdisc/
# Direct download: https://raw.githubusercontent.com/akhepcat/qdisc/master/qdisc


## Paths and definitions
tc=/sbin/tc
#ext=eth0		# Change for your device, or leave blank for automagic based on default route
ext_ingress=ifb0	# Use a unique ifb per rate limiter!

# Set these as per your provider's settings, at 90% to start with
scale=kbit

# these must be the same scale!
up_rate=256
down_rate=256

DEBUG=${DEBUG:-0}

## head -n 32 qdisc | tail -n +19 > /etc/default/qdisc
## and edit to your heart's content!
####################################

## for LSB init-style startup
[[ -r /lib/lsb/init-functions ]] && test run_by_init && . /lib/lsb/init-functions
# Are we running from init?
run_by_init() {
        if [ -n "${previous}" -a -n "${runlevel}" ]
        then
                return 0
        else
                return 1
        fi
}
lsb_log_begin() {
        MSG="$*"
        run_by_init && log_action_begin_msg "${MSG}" "${PROG}" || echo "BEGIN: ${MSG}"
}

lsb_log_end() {
        MSG="$*"
        run_by_init && log_action_end_msg "${MSG}" "${PROG}" || echo "END: ${MSG}"
}

lsb_log_fail() {
        MSG="$*"
        run_by_init && log_failure_msg "${MSG}" "${PROG}" || echo "FAIL: ${MSG}"
}

lsb_log_ok() {
        MSG="$*"
        run_by_init && log_success_msg "${MSG}" "${PROG}" || echo "SUCCESS: ${MSG}"
}

lsb_msg() {
        MSG="$*"
        run_by_init && log_action_msg "${MSG}" || echo "${MSG}"
}


[[ -r /etc/qdisc.conf ]] && . /etc/qdisc.conf
[[ -r /etc/default/qdisc ]] && . /etc/default/qdisc

if [ -n "$DEBUG" -a $DEBUG -gt 0 ]
then
	tc="echo $tc"
	set -x
fi

#if we don't have an external interface defined, or if the supplied one is 'wrong'
#try to guess it from the routing table.
if [ -z "$(ip link show | grep ${ext:-ENOSUCHIFACE})" ]
then
	EXT_4IF=$(awk 'BEGIN { IGNORECASE=1 } /^[a-z0-9:.-]+[ \t]+00000000/ { print $1 }' /proc/net/route 2>/dev/null | head -1)
	EXT_6IF=$(awk 'BEGIN { IGNORECASE=1 } /^00000000000000000000000000000000 00 00000000000000000000000000000000 00 / { if(!/lo/) print $10}' /proc/net/ipv6_route 2>/dev/null | head -1)

	if [ -z "${EXT_4IF//[^A-Za-z0-9]/}" ];
	then
	        # no default IPv4 interface.  Check for IPv6 first...
	        if [ -z "${EXT_6IF//[^A-Za-z0-9]/}" ];
	        then
	                # no IPv6 interface either, so we can't really continue
	                echo "No active network interface, bailing out"
	                exit 1
	        else
	                # there's an IPv6 interface, so we'll use that in case IPv4 comes up later
	                EXT_4IF="${EXT_6IF}"
	        fi
	else
	        # IPv4 is okay, so we'll short-circuit our test and assignment
	        EXT_6IF=${EXT_6IF:-$EXT_4IF}
	fi

	ext=${EXT_4IF:-$EXT_6IF}
fi

rate=$(( $up_rate > $down_rate ? $up_rate : $down_rate ))
iscale=${scale:0:1}

ratio=$(( $down_rate / $up_rate ))
if [ ${ratio:-1} -gt 10 -o ${ratio:-0} -eq 0 ]
then
	echo "ratio of download to upload (${down_rate}:${up_rate}) is greater than 10:1 (or zero)"
	echo "you may see issues trying to reach your maximum bandwidth"
fi

# this is a wild stab for GBit
q=1514
if [ "${iscale}" = "m" -o "${iscale}" = "g" ]
then
	if [ $rate -gt 100 -a "${iscale}" = "m" ]
	then
		q=4470
	elif [ \( $rate -gt 1000 -a "${iscale}" = "m" \) -o "${iscale}" = "g" ]
	then
		q=9270                  # HTB Quantum = 1500bytes IP + 14 bytes ethernet.
					# Higher bandwidths may require a higher htb quantum. MEASURE.
					# Some ADSL devices might require a stab setting.
	fi
fi

if [ ! \( \( $rate -ge 50 -a "${iscale}" = "m" \) -o "${iscale}" = "g" \) ]
then
	quantum=300		# fq_codel quantum 300 gives a boost to interactive flows
				# At higher bandwidths (50Mbit+) don't bother
fi

# manually tested values; rate=10m:r2q=6, rate=100m:r2q=63, rate=500m:r2q=313, rate=1gbit:r2q=625 -- gives us a curve!
if [ "${iscale}" = "m" -o "${iscale}" = "g" ]
then
	r2q=$(echo "( -0.000001111 * ($rate^2) ) + ( 0.6257 * $rate ) + 0.4444" | bc)
	r2q=${r2q%%.*}		# it's possible we could be off-by-one occasionally due to rounding, but whatever.

	# the default is 10, so if the math set it below 10, just kill the auto-set
	[[ ${r2q} -lt 10 ]] && unset r2q
else
	unset r2q
fi

pre_flight() {
	ifaces=$(ip link show | grep -vE 'noop|noqueue|ifb|master' | grep BROADCAST | cut -f 2 -d: | wc -l)
	ifaces=$((ifaces + 2))	# Breathing room,

	if [ -n "$(lsmod | grep ifb)" ]
	then
		numifbs=$(ip link show | grep -E 'ifb[0-9]' | wc -l )
		if [ ${numifbs:-0} -lt ${ifaces:-2} ]
		then
			unload
		fi
	fi
	if [ -z "$(lsmod | grep ifb)" ]
	then
		modprobe ifb numifbs=${ifaces:-2}
		modprobe sch_fq_codel
		modprobe act_mirred
	fi

	  # Also turn of gro on ALL interfaces 
	  # e.g ethtool -K eth1 gro off if you have eth1
	  # some devices you may need to run these 
	  # commands independently
	ethtool -K $ext tso off gso off gro off 2>&1 | grep -vi "Cannot change"

	# increase the TX queue length for higher speeds...
	txqlen=$(ifconfig -v $ext | grep txqueuelen | sed 's/.*txqueuelen[: ]\([0-9]\+\).*/\1/g;')
	if [ ${txqlen:-0} -lt 1000 -a ${rate:-0} -ge 250 ]
	then
		ifconfig $ext txqueuelen 1000
	fi
}

unload() {
	rmmod ifb sch_htb sch_ingress sch_fq_codel cls_flow cls_u32 act_mirred
}

# Clear old queuing disciplines (qdisc) on the interfaces
egress_down()
{
	$tc qdisc del dev $ext root 2>/dev/null
	$tc qdisc del dev $ext ingress 2>/dev/null
}

ingress_down()
{
	$tc qdisc del dev $ext_ingress root 2>/dev/null
	$tc qdisc del dev $ext_ingress ingress 2>/dev/null
}

#########
# INGRESS
#########

ingress_up()
{
	# Create ingress on external interface
	$tc qdisc add dev $ext handle ffff: ingress

	ifconfig $ext_ingress up # if the interace is not up bad things happen

	# Forward all ingress traffic to the IFB device
	$tc filter add dev $ext parent ffff: protocol all u32 match u32 0 0 action mirred egress redirect dev $ext_ingress

	# Create an EGRESS filter on the IFB device
	$tc qdisc add dev $ext_ingress root handle 1: htb default 11 ${r2q:+r2q $r2q}

	# Add root class HTB with rate limiting
	$tc class add dev $ext_ingress parent 1: classid 1:1 htb rate ${down_rate}${scale}
	$tc class add dev $ext_ingress parent 1:1 classid 1:11 htb rate ${down_rate}${scale} prio 0 ${q:+quantum $q}

	# Add FQ_CODEL qdisc with ECN support (if you want ecn)
	$tc qdisc add dev $ext_ingress parent 1:11 fq_codel ${quantum:+quantum $quantum} noecn
}

#########
# EGRESS
#########
egress_up()
{
	# Add FQ_CODEL to EGRESS on external interface
	$tc qdisc add dev $ext root handle 1: htb default 11 ${r2q:+r2q $r2q}

	# Add root class HTB with rate limiting
	$tc class add dev $ext parent 1: classid 1:1 htb rate ${up_rate}${scale}
	$tc class add dev $ext parent 1:1 classid 1:11 htb rate ${up_rate}${scale} prio 0 ${q:+quantum $q}

	# Note: You can apply a packet limit here and on ingress if you are memory constrained - e.g
	# for low bandwidths and machines with < 64MB of ram, limit 1000 is good, otherwise no point

	# Add FQ_CODEL qdisc without ECN support - on egress it's generally better to just drop the packet
	# but feel free to enable it if you want.

	$tc qdisc add dev $ext parent 1:11 fq_codel ${quantum:+quantum $quantum} noecn
}

stats() {
	if [ -z "$(lsmod | grep ifb)" ]
	then
		echo -e "qdisc queueing not enabled, running kernel defaults\n"
	else
		echo -e "queuing enabled on ${ext}/${ext_ingress}\n"
	fi
	$tc -s qdisc show dev $ext 2>/dev/null
	$tc -s filter show dev $ext parent ffff: 2>/dev/null
	$tc -s -d class show dev $ext_ingress 2>/dev/null
}

case "$1" in
	start|restart) lsb_log_begin "starting";pre_flight; egress_down; ingress_down; ingress_up; egress_up; stats; lsb_log_end 0;
		;;
	stop) lsb_log_begin "stopping";egress_down; ingress_down; lsb_log_end 0;
		;;
	start_ingress) lsb_log_begin "starting ingress only";pre_flight; ingress_down; ingress_up; lsb_log_end 0;
		;;
	start_egress) lsb_log_begin "starting egress only";pre_flight; egress_down; egress_up; lsb_log_end 0;
		;;
	flush) lsb_log_begin "flushing";egress_down; ingress_down; unload; lsb_log_end 0;
		;;
	status) stats
		;;
	*) echo "$0 [start|stop]{_ingress|_egress} | restart | flush | status"
		;;
esac

if [ -n "$DEBUG" -a $DEBUG -gt 0 ]
then
	#only if we set it..., don't carry it out
	set +x
fi
